dist: xenial
#before_install:
#  - sudo apt-get install -y hugo
addons:
  snaps:
  - hugo

install:
  - rm -rf public || exit 0
script: 
  - git clone https://$GITHUB_TOKEN@github.com/atovk/atovk.github.io.git public
  - hugo
# 
#deploy:
#  edge:
#    branch: v1.8.47
#  provider: pages
#  skip_cleanup: true
#  repo: atovk/atovk.github.io.git
#  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
#  local_dir: piblic
#  target_branch: master
#  keep_history: true
#  on:
#    branch: master
after_success:
  - cd public
  - ls
  - git add .
  - git commit -m "Travis upate $(date "+%Y-%m-%d^%H:%M:%S")" 
  - git push -u origin master